# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.25.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.25.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/haiduong/daisykit

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/haiduong/daisykit

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.25.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.25.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.25.3/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.25.3/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.25.3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.25.3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.25.3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.25.3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/haiduong/daisykit/CMakeFiles /Users/haiduong/daisykit//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/haiduong/daisykit/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named daisykitsdk

# Build rule for target.
daisykitsdk: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 daisykitsdk
.PHONY : daisykitsdk

# fast build rule for target.
daisykitsdk/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/build
.PHONY : daisykitsdk/fast

#=============================================================================
# Target rules for targets named configs

# Build rule for target.
configs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 configs
.PHONY : configs

# fast build rule for target.
configs/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/configs.dir/build.make CMakeFiles/configs.dir/build
.PHONY : configs/fast

#=============================================================================
# Target rules for targets named models

# Build rule for target.
models: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 models
.PHONY : models

# fast build rule for target.
models/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/models.dir/build.make CMakeFiles/models.dir/build
.PHONY : models/fast

#=============================================================================
# Target rules for targets named images

# Build rule for target.
images: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 images
.PHONY : images

# fast build rule for target.
images/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/images.dir/build.make CMakeFiles/images.dir/build
.PHONY : images/fast

#=============================================================================
# Target rules for targets named ncnn-generate-spirv

# Build rule for target.
ncnn-generate-spirv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ncnn-generate-spirv
.PHONY : ncnn-generate-spirv

# fast build rule for target.
ncnn-generate-spirv/fast:
	$(MAKE) $(MAKESILENT) -f bin_ncnn/src/CMakeFiles/ncnn-generate-spirv.dir/build.make bin_ncnn/src/CMakeFiles/ncnn-generate-spirv.dir/build
.PHONY : ncnn-generate-spirv/fast

#=============================================================================
# Target rules for targets named ncnn

# Build rule for target.
ncnn: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ncnn
.PHONY : ncnn

# fast build rule for target.
ncnn/fast:
	$(MAKE) $(MAKESILENT) -f bin_ncnn/src/CMakeFiles/ncnn.dir/build.make bin_ncnn/src/CMakeFiles/ncnn.dir/build
.PHONY : ncnn/fast

#=============================================================================
# Target rules for targets named ZXing

# Build rule for target.
ZXing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ZXing
.PHONY : ZXing

# fast build rule for target.
ZXing/fast:
	$(MAKE) $(MAKESILENT) -f third_party/zxing-cpp/CMakeFiles/ZXing.dir/build.make third_party/zxing-cpp/CMakeFiles/ZXing.dir/build
.PHONY : ZXing/fast

#=============================================================================
# Target rules for targets named demo_pushup_classifier

# Build rule for target.
demo_pushup_classifier: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_pushup_classifier
.PHONY : demo_pushup_classifier

# fast build rule for target.
demo_pushup_classifier/fast:
	$(MAKE) $(MAKESILENT) -f src/examples/CMakeFiles/demo_pushup_classifier.dir/build.make src/examples/CMakeFiles/demo_pushup_classifier.dir/build
.PHONY : demo_pushup_classifier/fast

#=============================================================================
# Target rules for targets named demo_pushup_full

# Build rule for target.
demo_pushup_full: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_pushup_full
.PHONY : demo_pushup_full

# fast build rule for target.
demo_pushup_full/fast:
	$(MAKE) $(MAKESILENT) -f src/examples/CMakeFiles/demo_pushup_full.dir/build.make src/examples/CMakeFiles/demo_pushup_full.dir/build
.PHONY : demo_pushup_full/fast

#=============================================================================
# Target rules for targets named demo_barcode_scanner

# Build rule for target.
demo_barcode_scanner: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_barcode_scanner
.PHONY : demo_barcode_scanner

# fast build rule for target.
demo_barcode_scanner/fast:
	$(MAKE) $(MAKESILENT) -f src/examples/CMakeFiles/demo_barcode_scanner.dir/build.make src/examples/CMakeFiles/demo_barcode_scanner.dir/build
.PHONY : demo_barcode_scanner/fast

#=============================================================================
# Target rules for targets named demo_face_detector

# Build rule for target.
demo_face_detector: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_face_detector
.PHONY : demo_face_detector

# fast build rule for target.
demo_face_detector/fast:
	$(MAKE) $(MAKESILENT) -f src/examples/CMakeFiles/demo_face_detector.dir/build.make src/examples/CMakeFiles/demo_face_detector.dir/build
.PHONY : demo_face_detector/fast

#=============================================================================
# Target rules for targets named demo_background_matting

# Build rule for target.
demo_background_matting: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_background_matting
.PHONY : demo_background_matting

# fast build rule for target.
demo_background_matting/fast:
	$(MAKE) $(MAKESILENT) -f src/examples/CMakeFiles/demo_background_matting.dir/build.make src/examples/CMakeFiles/demo_background_matting.dir/build
.PHONY : demo_background_matting/fast

#=============================================================================
# Target rules for targets named demo_graph_api

# Build rule for target.
demo_graph_api: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_graph_api
.PHONY : demo_graph_api

# fast build rule for target.
demo_graph_api/fast:
	$(MAKE) $(MAKESILENT) -f src/examples/CMakeFiles/demo_graph_api.dir/build.make src/examples/CMakeFiles/demo_graph_api.dir/build
.PHONY : demo_graph_api/fast

#=============================================================================
# Target rules for targets named demo_face_detector_graph

# Build rule for target.
demo_face_detector_graph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_face_detector_graph
.PHONY : demo_face_detector_graph

# fast build rule for target.
demo_face_detector_graph/fast:
	$(MAKE) $(MAKESILENT) -f src/examples/CMakeFiles/demo_face_detector_graph.dir/build.make src/examples/CMakeFiles/demo_face_detector_graph.dir/build
.PHONY : demo_face_detector_graph/fast

#=============================================================================
# Target rules for targets named demo_movenet

# Build rule for target.
demo_movenet: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_movenet
.PHONY : demo_movenet

# fast build rule for target.
demo_movenet/fast:
	$(MAKE) $(MAKESILENT) -f src/examples/CMakeFiles/demo_movenet.dir/build.make src/examples/CMakeFiles/demo_movenet.dir/build
.PHONY : demo_movenet/fast

#=============================================================================
# Target rules for targets named demo_hand_detector_yolox

# Build rule for target.
demo_hand_detector_yolox: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_hand_detector_yolox
.PHONY : demo_hand_detector_yolox

# fast build rule for target.
demo_hand_detector_yolox/fast:
	$(MAKE) $(MAKESILENT) -f src/examples/CMakeFiles/demo_hand_detector_yolox.dir/build.make src/examples/CMakeFiles/demo_hand_detector_yolox.dir/build
.PHONY : demo_hand_detector_yolox/fast

#=============================================================================
# Target rules for targets named demo_hand_pose_detector

# Build rule for target.
demo_hand_pose_detector: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_hand_pose_detector
.PHONY : demo_hand_pose_detector

# fast build rule for target.
demo_hand_pose_detector/fast:
	$(MAKE) $(MAKESILENT) -f src/examples/CMakeFiles/demo_hand_pose_detector.dir/build.make src/examples/CMakeFiles/demo_hand_pose_detector.dir/build
.PHONY : demo_hand_pose_detector/fast

#=============================================================================
# Target rules for targets named demo_object_detector

# Build rule for target.
demo_object_detector: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_object_detector
.PHONY : demo_object_detector

# fast build rule for target.
demo_object_detector/fast:
	$(MAKE) $(MAKESILENT) -f src/examples/CMakeFiles/demo_object_detector.dir/build.make src/examples/CMakeFiles/demo_object_detector.dir/build
.PHONY : demo_object_detector/fast

#=============================================================================
# Target rules for targets named demo_face_detector_scrfd

# Build rule for target.
demo_face_detector_scrfd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_face_detector_scrfd
.PHONY : demo_face_detector_scrfd

# fast build rule for target.
demo_face_detector_scrfd/fast:
	$(MAKE) $(MAKESILENT) -f src/examples/CMakeFiles/demo_face_detector_scrfd.dir/build.make src/examples/CMakeFiles/demo_face_detector_scrfd.dir/build
.PHONY : demo_face_detector_scrfd/fast

#=============================================================================
# Target rules for targets named demo_face_sequential

# Build rule for target.
demo_face_sequential: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_face_sequential
.PHONY : demo_face_sequential

# fast build rule for target.
demo_face_sequential/fast:
	$(MAKE) $(MAKESILENT) -f src/examples/CMakeFiles/demo_face_sequential.dir/build.make src/examples/CMakeFiles/demo_face_sequential.dir/build
.PHONY : demo_face_sequential/fast

src/common/io/data_reader.o: src/common/io/data_reader.cpp.o
.PHONY : src/common/io/data_reader.o

# target to build an object file
src/common/io/data_reader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/common/io/data_reader.cpp.o
.PHONY : src/common/io/data_reader.cpp.o

src/common/io/data_reader.i: src/common/io/data_reader.cpp.i
.PHONY : src/common/io/data_reader.i

# target to preprocess a source file
src/common/io/data_reader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/common/io/data_reader.cpp.i
.PHONY : src/common/io/data_reader.cpp.i

src/common/io/data_reader.s: src/common/io/data_reader.cpp.s
.PHONY : src/common/io/data_reader.s

# target to generate assembly for a file
src/common/io/data_reader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/common/io/data_reader.cpp.s
.PHONY : src/common/io/data_reader.cpp.s

src/common/profiler.o: src/common/profiler.cpp.o
.PHONY : src/common/profiler.o

# target to build an object file
src/common/profiler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/common/profiler.cpp.o
.PHONY : src/common/profiler.cpp.o

src/common/profiler.i: src/common/profiler.cpp.i
.PHONY : src/common/profiler.i

# target to preprocess a source file
src/common/profiler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/common/profiler.cpp.i
.PHONY : src/common/profiler.cpp.i

src/common/profiler.s: src/common/profiler.cpp.s
.PHONY : src/common/profiler.s

# target to generate assembly for a file
src/common/profiler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/common/profiler.cpp.s
.PHONY : src/common/profiler.cpp.s

src/common/utils/timer.o: src/common/utils/timer.cpp.o
.PHONY : src/common/utils/timer.o

# target to build an object file
src/common/utils/timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/common/utils/timer.cpp.o
.PHONY : src/common/utils/timer.cpp.o

src/common/utils/timer.i: src/common/utils/timer.cpp.i
.PHONY : src/common/utils/timer.i

# target to preprocess a source file
src/common/utils/timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/common/utils/timer.cpp.i
.PHONY : src/common/utils/timer.cpp.i

src/common/utils/timer.s: src/common/utils/timer.cpp.s
.PHONY : src/common/utils/timer.s

# target to generate assembly for a file
src/common/utils/timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/common/utils/timer.cpp.s
.PHONY : src/common/utils/timer.cpp.s

src/common/visualizers/base_visualizer.o: src/common/visualizers/base_visualizer.cpp.o
.PHONY : src/common/visualizers/base_visualizer.o

# target to build an object file
src/common/visualizers/base_visualizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/common/visualizers/base_visualizer.cpp.o
.PHONY : src/common/visualizers/base_visualizer.cpp.o

src/common/visualizers/base_visualizer.i: src/common/visualizers/base_visualizer.cpp.i
.PHONY : src/common/visualizers/base_visualizer.i

# target to preprocess a source file
src/common/visualizers/base_visualizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/common/visualizers/base_visualizer.cpp.i
.PHONY : src/common/visualizers/base_visualizer.cpp.i

src/common/visualizers/base_visualizer.s: src/common/visualizers/base_visualizer.cpp.s
.PHONY : src/common/visualizers/base_visualizer.s

# target to generate assembly for a file
src/common/visualizers/base_visualizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/common/visualizers/base_visualizer.cpp.s
.PHONY : src/common/visualizers/base_visualizer.cpp.s

src/flows/background_matting_flow.o: src/flows/background_matting_flow.cpp.o
.PHONY : src/flows/background_matting_flow.o

# target to build an object file
src/flows/background_matting_flow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/flows/background_matting_flow.cpp.o
.PHONY : src/flows/background_matting_flow.cpp.o

src/flows/background_matting_flow.i: src/flows/background_matting_flow.cpp.i
.PHONY : src/flows/background_matting_flow.i

# target to preprocess a source file
src/flows/background_matting_flow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/flows/background_matting_flow.cpp.i
.PHONY : src/flows/background_matting_flow.cpp.i

src/flows/background_matting_flow.s: src/flows/background_matting_flow.cpp.s
.PHONY : src/flows/background_matting_flow.s

# target to generate assembly for a file
src/flows/background_matting_flow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/flows/background_matting_flow.cpp.s
.PHONY : src/flows/background_matting_flow.cpp.s

src/flows/barcode_scanner_flow.o: src/flows/barcode_scanner_flow.cpp.o
.PHONY : src/flows/barcode_scanner_flow.o

# target to build an object file
src/flows/barcode_scanner_flow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/flows/barcode_scanner_flow.cpp.o
.PHONY : src/flows/barcode_scanner_flow.cpp.o

src/flows/barcode_scanner_flow.i: src/flows/barcode_scanner_flow.cpp.i
.PHONY : src/flows/barcode_scanner_flow.i

# target to preprocess a source file
src/flows/barcode_scanner_flow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/flows/barcode_scanner_flow.cpp.i
.PHONY : src/flows/barcode_scanner_flow.cpp.i

src/flows/barcode_scanner_flow.s: src/flows/barcode_scanner_flow.cpp.s
.PHONY : src/flows/barcode_scanner_flow.s

# target to generate assembly for a file
src/flows/barcode_scanner_flow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/flows/barcode_scanner_flow.cpp.s
.PHONY : src/flows/barcode_scanner_flow.cpp.s

src/flows/face_detector_flow.o: src/flows/face_detector_flow.cpp.o
.PHONY : src/flows/face_detector_flow.o

# target to build an object file
src/flows/face_detector_flow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/flows/face_detector_flow.cpp.o
.PHONY : src/flows/face_detector_flow.cpp.o

src/flows/face_detector_flow.i: src/flows/face_detector_flow.cpp.i
.PHONY : src/flows/face_detector_flow.i

# target to preprocess a source file
src/flows/face_detector_flow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/flows/face_detector_flow.cpp.i
.PHONY : src/flows/face_detector_flow.cpp.i

src/flows/face_detector_flow.s: src/flows/face_detector_flow.cpp.s
.PHONY : src/flows/face_detector_flow.s

# target to generate assembly for a file
src/flows/face_detector_flow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/flows/face_detector_flow.cpp.s
.PHONY : src/flows/face_detector_flow.cpp.s

src/flows/hand_pose_detector_flow.o: src/flows/hand_pose_detector_flow.cpp.o
.PHONY : src/flows/hand_pose_detector_flow.o

# target to build an object file
src/flows/hand_pose_detector_flow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/flows/hand_pose_detector_flow.cpp.o
.PHONY : src/flows/hand_pose_detector_flow.cpp.o

src/flows/hand_pose_detector_flow.i: src/flows/hand_pose_detector_flow.cpp.i
.PHONY : src/flows/hand_pose_detector_flow.i

# target to preprocess a source file
src/flows/hand_pose_detector_flow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/flows/hand_pose_detector_flow.cpp.i
.PHONY : src/flows/hand_pose_detector_flow.cpp.i

src/flows/hand_pose_detector_flow.s: src/flows/hand_pose_detector_flow.cpp.s
.PHONY : src/flows/hand_pose_detector_flow.s

# target to generate assembly for a file
src/flows/hand_pose_detector_flow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/flows/hand_pose_detector_flow.cpp.s
.PHONY : src/flows/hand_pose_detector_flow.cpp.s

src/flows/human_pose_movenet_flow.o: src/flows/human_pose_movenet_flow.cpp.o
.PHONY : src/flows/human_pose_movenet_flow.o

# target to build an object file
src/flows/human_pose_movenet_flow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/flows/human_pose_movenet_flow.cpp.o
.PHONY : src/flows/human_pose_movenet_flow.cpp.o

src/flows/human_pose_movenet_flow.i: src/flows/human_pose_movenet_flow.cpp.i
.PHONY : src/flows/human_pose_movenet_flow.i

# target to preprocess a source file
src/flows/human_pose_movenet_flow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/flows/human_pose_movenet_flow.cpp.i
.PHONY : src/flows/human_pose_movenet_flow.cpp.i

src/flows/human_pose_movenet_flow.s: src/flows/human_pose_movenet_flow.cpp.s
.PHONY : src/flows/human_pose_movenet_flow.s

# target to generate assembly for a file
src/flows/human_pose_movenet_flow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/flows/human_pose_movenet_flow.cpp.s
.PHONY : src/flows/human_pose_movenet_flow.cpp.s

src/flows/object_detector_flow.o: src/flows/object_detector_flow.cpp.o
.PHONY : src/flows/object_detector_flow.o

# target to build an object file
src/flows/object_detector_flow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/flows/object_detector_flow.cpp.o
.PHONY : src/flows/object_detector_flow.cpp.o

src/flows/object_detector_flow.i: src/flows/object_detector_flow.cpp.i
.PHONY : src/flows/object_detector_flow.i

# target to preprocess a source file
src/flows/object_detector_flow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/flows/object_detector_flow.cpp.i
.PHONY : src/flows/object_detector_flow.cpp.i

src/flows/object_detector_flow.s: src/flows/object_detector_flow.cpp.s
.PHONY : src/flows/object_detector_flow.s

# target to generate assembly for a file
src/flows/object_detector_flow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/flows/object_detector_flow.cpp.s
.PHONY : src/flows/object_detector_flow.cpp.s

src/flows/pushup_counter_flow.o: src/flows/pushup_counter_flow.cpp.o
.PHONY : src/flows/pushup_counter_flow.o

# target to build an object file
src/flows/pushup_counter_flow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/flows/pushup_counter_flow.cpp.o
.PHONY : src/flows/pushup_counter_flow.cpp.o

src/flows/pushup_counter_flow.i: src/flows/pushup_counter_flow.cpp.i
.PHONY : src/flows/pushup_counter_flow.i

# target to preprocess a source file
src/flows/pushup_counter_flow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/flows/pushup_counter_flow.cpp.i
.PHONY : src/flows/pushup_counter_flow.cpp.i

src/flows/pushup_counter_flow.s: src/flows/pushup_counter_flow.cpp.s
.PHONY : src/flows/pushup_counter_flow.s

# target to generate assembly for a file
src/flows/pushup_counter_flow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/flows/pushup_counter_flow.cpp.s
.PHONY : src/flows/pushup_counter_flow.cpp.s

src/graphs/core/connection.o: src/graphs/core/connection.cpp.o
.PHONY : src/graphs/core/connection.o

# target to build an object file
src/graphs/core/connection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/graphs/core/connection.cpp.o
.PHONY : src/graphs/core/connection.cpp.o

src/graphs/core/connection.i: src/graphs/core/connection.cpp.i
.PHONY : src/graphs/core/connection.i

# target to preprocess a source file
src/graphs/core/connection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/graphs/core/connection.cpp.i
.PHONY : src/graphs/core/connection.cpp.i

src/graphs/core/connection.s: src/graphs/core/connection.cpp.s
.PHONY : src/graphs/core/connection.s

# target to generate assembly for a file
src/graphs/core/connection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/graphs/core/connection.cpp.s
.PHONY : src/graphs/core/connection.cpp.s

src/graphs/core/graph.o: src/graphs/core/graph.cpp.o
.PHONY : src/graphs/core/graph.o

# target to build an object file
src/graphs/core/graph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/graphs/core/graph.cpp.o
.PHONY : src/graphs/core/graph.cpp.o

src/graphs/core/graph.i: src/graphs/core/graph.cpp.i
.PHONY : src/graphs/core/graph.i

# target to preprocess a source file
src/graphs/core/graph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/graphs/core/graph.cpp.i
.PHONY : src/graphs/core/graph.cpp.i

src/graphs/core/graph.s: src/graphs/core/graph.cpp.s
.PHONY : src/graphs/core/graph.s

# target to generate assembly for a file
src/graphs/core/graph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/graphs/core/graph.cpp.s
.PHONY : src/graphs/core/graph.cpp.s

src/graphs/core/node.o: src/graphs/core/node.cpp.o
.PHONY : src/graphs/core/node.o

# target to build an object file
src/graphs/core/node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/graphs/core/node.cpp.o
.PHONY : src/graphs/core/node.cpp.o

src/graphs/core/node.i: src/graphs/core/node.cpp.i
.PHONY : src/graphs/core/node.i

# target to preprocess a source file
src/graphs/core/node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/graphs/core/node.cpp.i
.PHONY : src/graphs/core/node.cpp.i

src/graphs/core/node.s: src/graphs/core/node.cpp.s
.PHONY : src/graphs/core/node.s

# target to generate assembly for a file
src/graphs/core/node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/graphs/core/node.cpp.s
.PHONY : src/graphs/core/node.cpp.s

src/graphs/core/packet.o: src/graphs/core/packet.cpp.o
.PHONY : src/graphs/core/packet.o

# target to build an object file
src/graphs/core/packet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/graphs/core/packet.cpp.o
.PHONY : src/graphs/core/packet.cpp.o

src/graphs/core/packet.i: src/graphs/core/packet.cpp.i
.PHONY : src/graphs/core/packet.i

# target to preprocess a source file
src/graphs/core/packet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/graphs/core/packet.cpp.i
.PHONY : src/graphs/core/packet.cpp.i

src/graphs/core/packet.s: src/graphs/core/packet.cpp.s
.PHONY : src/graphs/core/packet.s

# target to generate assembly for a file
src/graphs/core/packet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/graphs/core/packet.cpp.s
.PHONY : src/graphs/core/packet.cpp.s

src/graphs/core/transmission_profile.o: src/graphs/core/transmission_profile.cpp.o
.PHONY : src/graphs/core/transmission_profile.o

# target to build an object file
src/graphs/core/transmission_profile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/graphs/core/transmission_profile.cpp.o
.PHONY : src/graphs/core/transmission_profile.cpp.o

src/graphs/core/transmission_profile.i: src/graphs/core/transmission_profile.cpp.i
.PHONY : src/graphs/core/transmission_profile.i

# target to preprocess a source file
src/graphs/core/transmission_profile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/graphs/core/transmission_profile.cpp.i
.PHONY : src/graphs/core/transmission_profile.cpp.i

src/graphs/core/transmission_profile.s: src/graphs/core/transmission_profile.cpp.s
.PHONY : src/graphs/core/transmission_profile.s

# target to generate assembly for a file
src/graphs/core/transmission_profile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/graphs/core/transmission_profile.cpp.s
.PHONY : src/graphs/core/transmission_profile.cpp.s

src/models/action_classifier.o: src/models/action_classifier.cpp.o
.PHONY : src/models/action_classifier.o

# target to build an object file
src/models/action_classifier.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/action_classifier.cpp.o
.PHONY : src/models/action_classifier.cpp.o

src/models/action_classifier.i: src/models/action_classifier.cpp.i
.PHONY : src/models/action_classifier.i

# target to preprocess a source file
src/models/action_classifier.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/action_classifier.cpp.i
.PHONY : src/models/action_classifier.cpp.i

src/models/action_classifier.s: src/models/action_classifier.cpp.s
.PHONY : src/models/action_classifier.s

# target to generate assembly for a file
src/models/action_classifier.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/action_classifier.cpp.s
.PHONY : src/models/action_classifier.cpp.s

src/models/background_matting.o: src/models/background_matting.cpp.o
.PHONY : src/models/background_matting.o

# target to build an object file
src/models/background_matting.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/background_matting.cpp.o
.PHONY : src/models/background_matting.cpp.o

src/models/background_matting.i: src/models/background_matting.cpp.i
.PHONY : src/models/background_matting.i

# target to preprocess a source file
src/models/background_matting.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/background_matting.cpp.i
.PHONY : src/models/background_matting.cpp.i

src/models/background_matting.s: src/models/background_matting.cpp.s
.PHONY : src/models/background_matting.s

# target to generate assembly for a file
src/models/background_matting.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/background_matting.cpp.s
.PHONY : src/models/background_matting.cpp.s

src/models/body_detector.o: src/models/body_detector.cpp.o
.PHONY : src/models/body_detector.o

# target to build an object file
src/models/body_detector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/body_detector.cpp.o
.PHONY : src/models/body_detector.cpp.o

src/models/body_detector.i: src/models/body_detector.cpp.i
.PHONY : src/models/body_detector.i

# target to preprocess a source file
src/models/body_detector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/body_detector.cpp.i
.PHONY : src/models/body_detector.cpp.i

src/models/body_detector.s: src/models/body_detector.cpp.s
.PHONY : src/models/body_detector.s

# target to generate assembly for a file
src/models/body_detector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/body_detector.cpp.s
.PHONY : src/models/body_detector.cpp.s

src/models/face_detector.o: src/models/face_detector.cpp.o
.PHONY : src/models/face_detector.o

# target to build an object file
src/models/face_detector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/face_detector.cpp.o
.PHONY : src/models/face_detector.cpp.o

src/models/face_detector.i: src/models/face_detector.cpp.i
.PHONY : src/models/face_detector.i

# target to preprocess a source file
src/models/face_detector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/face_detector.cpp.i
.PHONY : src/models/face_detector.cpp.i

src/models/face_detector.s: src/models/face_detector.cpp.s
.PHONY : src/models/face_detector.s

# target to generate assembly for a file
src/models/face_detector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/face_detector.cpp.s
.PHONY : src/models/face_detector.cpp.s

src/models/face_recognition/face_alignment.o: src/models/face_recognition/face_alignment.cpp.o
.PHONY : src/models/face_recognition/face_alignment.o

# target to build an object file
src/models/face_recognition/face_alignment.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/face_recognition/face_alignment.cpp.o
.PHONY : src/models/face_recognition/face_alignment.cpp.o

src/models/face_recognition/face_alignment.i: src/models/face_recognition/face_alignment.cpp.i
.PHONY : src/models/face_recognition/face_alignment.i

# target to preprocess a source file
src/models/face_recognition/face_alignment.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/face_recognition/face_alignment.cpp.i
.PHONY : src/models/face_recognition/face_alignment.cpp.i

src/models/face_recognition/face_alignment.s: src/models/face_recognition/face_alignment.cpp.s
.PHONY : src/models/face_recognition/face_alignment.s

# target to generate assembly for a file
src/models/face_recognition/face_alignment.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/face_recognition/face_alignment.cpp.s
.PHONY : src/models/face_recognition/face_alignment.cpp.s

src/models/face_recognition/face_detector_scrfd.o: src/models/face_recognition/face_detector_scrfd.cpp.o
.PHONY : src/models/face_recognition/face_detector_scrfd.o

# target to build an object file
src/models/face_recognition/face_detector_scrfd.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/face_recognition/face_detector_scrfd.cpp.o
.PHONY : src/models/face_recognition/face_detector_scrfd.cpp.o

src/models/face_recognition/face_detector_scrfd.i: src/models/face_recognition/face_detector_scrfd.cpp.i
.PHONY : src/models/face_recognition/face_detector_scrfd.i

# target to preprocess a source file
src/models/face_recognition/face_detector_scrfd.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/face_recognition/face_detector_scrfd.cpp.i
.PHONY : src/models/face_recognition/face_detector_scrfd.cpp.i

src/models/face_recognition/face_detector_scrfd.s: src/models/face_recognition/face_detector_scrfd.cpp.s
.PHONY : src/models/face_recognition/face_detector_scrfd.s

# target to generate assembly for a file
src/models/face_recognition/face_detector_scrfd.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/face_recognition/face_detector_scrfd.cpp.s
.PHONY : src/models/face_recognition/face_detector_scrfd.cpp.s

src/models/face_recognition/face_extractor.o: src/models/face_recognition/face_extractor.cpp.o
.PHONY : src/models/face_recognition/face_extractor.o

# target to build an object file
src/models/face_recognition/face_extractor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/face_recognition/face_extractor.cpp.o
.PHONY : src/models/face_recognition/face_extractor.cpp.o

src/models/face_recognition/face_extractor.i: src/models/face_recognition/face_extractor.cpp.i
.PHONY : src/models/face_recognition/face_extractor.i

# target to preprocess a source file
src/models/face_recognition/face_extractor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/face_recognition/face_extractor.cpp.i
.PHONY : src/models/face_recognition/face_extractor.cpp.i

src/models/face_recognition/face_extractor.s: src/models/face_recognition/face_extractor.cpp.s
.PHONY : src/models/face_recognition/face_extractor.s

# target to generate assembly for a file
src/models/face_recognition/face_extractor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/face_recognition/face_extractor.cpp.s
.PHONY : src/models/face_recognition/face_extractor.cpp.s

src/models/face_recognition/face_manager.o: src/models/face_recognition/face_manager.cpp.o
.PHONY : src/models/face_recognition/face_manager.o

# target to build an object file
src/models/face_recognition/face_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/face_recognition/face_manager.cpp.o
.PHONY : src/models/face_recognition/face_manager.cpp.o

src/models/face_recognition/face_manager.i: src/models/face_recognition/face_manager.cpp.i
.PHONY : src/models/face_recognition/face_manager.i

# target to preprocess a source file
src/models/face_recognition/face_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/face_recognition/face_manager.cpp.i
.PHONY : src/models/face_recognition/face_manager.cpp.i

src/models/face_recognition/face_manager.s: src/models/face_recognition/face_manager.cpp.s
.PHONY : src/models/face_recognition/face_manager.s

# target to generate assembly for a file
src/models/face_recognition/face_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/face_recognition/face_manager.cpp.s
.PHONY : src/models/face_recognition/face_manager.cpp.s

src/models/facial_landmark_detector.o: src/models/facial_landmark_detector.cpp.o
.PHONY : src/models/facial_landmark_detector.o

# target to build an object file
src/models/facial_landmark_detector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/facial_landmark_detector.cpp.o
.PHONY : src/models/facial_landmark_detector.cpp.o

src/models/facial_landmark_detector.i: src/models/facial_landmark_detector.cpp.i
.PHONY : src/models/facial_landmark_detector.i

# target to preprocess a source file
src/models/facial_landmark_detector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/facial_landmark_detector.cpp.i
.PHONY : src/models/facial_landmark_detector.cpp.i

src/models/facial_landmark_detector.s: src/models/facial_landmark_detector.cpp.s
.PHONY : src/models/facial_landmark_detector.s

# target to generate assembly for a file
src/models/facial_landmark_detector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/facial_landmark_detector.cpp.s
.PHONY : src/models/facial_landmark_detector.cpp.s

src/models/hand_detector_yolox.o: src/models/hand_detector_yolox.cpp.o
.PHONY : src/models/hand_detector_yolox.o

# target to build an object file
src/models/hand_detector_yolox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/hand_detector_yolox.cpp.o
.PHONY : src/models/hand_detector_yolox.cpp.o

src/models/hand_detector_yolox.i: src/models/hand_detector_yolox.cpp.i
.PHONY : src/models/hand_detector_yolox.i

# target to preprocess a source file
src/models/hand_detector_yolox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/hand_detector_yolox.cpp.i
.PHONY : src/models/hand_detector_yolox.cpp.i

src/models/hand_detector_yolox.s: src/models/hand_detector_yolox.cpp.s
.PHONY : src/models/hand_detector_yolox.s

# target to generate assembly for a file
src/models/hand_detector_yolox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/hand_detector_yolox.cpp.s
.PHONY : src/models/hand_detector_yolox.cpp.s

src/models/hand_pose_detector.o: src/models/hand_pose_detector.cpp.o
.PHONY : src/models/hand_pose_detector.o

# target to build an object file
src/models/hand_pose_detector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/hand_pose_detector.cpp.o
.PHONY : src/models/hand_pose_detector.cpp.o

src/models/hand_pose_detector.i: src/models/hand_pose_detector.cpp.i
.PHONY : src/models/hand_pose_detector.i

# target to preprocess a source file
src/models/hand_pose_detector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/hand_pose_detector.cpp.i
.PHONY : src/models/hand_pose_detector.cpp.i

src/models/hand_pose_detector.s: src/models/hand_pose_detector.cpp.s
.PHONY : src/models/hand_pose_detector.s

# target to generate assembly for a file
src/models/hand_pose_detector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/hand_pose_detector.cpp.s
.PHONY : src/models/hand_pose_detector.cpp.s

src/models/image_model.o: src/models/image_model.cpp.o
.PHONY : src/models/image_model.o

# target to build an object file
src/models/image_model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/image_model.cpp.o
.PHONY : src/models/image_model.cpp.o

src/models/image_model.i: src/models/image_model.cpp.i
.PHONY : src/models/image_model.i

# target to preprocess a source file
src/models/image_model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/image_model.cpp.i
.PHONY : src/models/image_model.cpp.i

src/models/image_model.s: src/models/image_model.cpp.s
.PHONY : src/models/image_model.s

# target to generate assembly for a file
src/models/image_model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/image_model.cpp.s
.PHONY : src/models/image_model.cpp.s

src/models/liveness_detector.o: src/models/liveness_detector.cpp.o
.PHONY : src/models/liveness_detector.o

# target to build an object file
src/models/liveness_detector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/liveness_detector.cpp.o
.PHONY : src/models/liveness_detector.cpp.o

src/models/liveness_detector.i: src/models/liveness_detector.cpp.i
.PHONY : src/models/liveness_detector.i

# target to preprocess a source file
src/models/liveness_detector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/liveness_detector.cpp.i
.PHONY : src/models/liveness_detector.cpp.i

src/models/liveness_detector.s: src/models/liveness_detector.cpp.s
.PHONY : src/models/liveness_detector.s

# target to generate assembly for a file
src/models/liveness_detector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/liveness_detector.cpp.s
.PHONY : src/models/liveness_detector.cpp.s

src/models/ncnn_model.o: src/models/ncnn_model.cpp.o
.PHONY : src/models/ncnn_model.o

# target to build an object file
src/models/ncnn_model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/ncnn_model.cpp.o
.PHONY : src/models/ncnn_model.cpp.o

src/models/ncnn_model.i: src/models/ncnn_model.cpp.i
.PHONY : src/models/ncnn_model.i

# target to preprocess a source file
src/models/ncnn_model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/ncnn_model.cpp.i
.PHONY : src/models/ncnn_model.cpp.i

src/models/ncnn_model.s: src/models/ncnn_model.cpp.s
.PHONY : src/models/ncnn_model.s

# target to generate assembly for a file
src/models/ncnn_model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/ncnn_model.cpp.s
.PHONY : src/models/ncnn_model.cpp.s

src/models/object_detector_yolox.o: src/models/object_detector_yolox.cpp.o
.PHONY : src/models/object_detector_yolox.o

# target to build an object file
src/models/object_detector_yolox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/object_detector_yolox.cpp.o
.PHONY : src/models/object_detector_yolox.cpp.o

src/models/object_detector_yolox.i: src/models/object_detector_yolox.cpp.i
.PHONY : src/models/object_detector_yolox.i

# target to preprocess a source file
src/models/object_detector_yolox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/object_detector_yolox.cpp.i
.PHONY : src/models/object_detector_yolox.cpp.i

src/models/object_detector_yolox.s: src/models/object_detector_yolox.cpp.s
.PHONY : src/models/object_detector_yolox.s

# target to generate assembly for a file
src/models/object_detector_yolox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/object_detector_yolox.cpp.s
.PHONY : src/models/object_detector_yolox.cpp.s

src/models/pose_detector.o: src/models/pose_detector.cpp.o
.PHONY : src/models/pose_detector.o

# target to build an object file
src/models/pose_detector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/pose_detector.cpp.o
.PHONY : src/models/pose_detector.cpp.o

src/models/pose_detector.i: src/models/pose_detector.cpp.i
.PHONY : src/models/pose_detector.i

# target to preprocess a source file
src/models/pose_detector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/pose_detector.cpp.i
.PHONY : src/models/pose_detector.cpp.i

src/models/pose_detector.s: src/models/pose_detector.cpp.s
.PHONY : src/models/pose_detector.s

# target to generate assembly for a file
src/models/pose_detector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/pose_detector.cpp.s
.PHONY : src/models/pose_detector.cpp.s

src/models/pose_detector_movenet.o: src/models/pose_detector_movenet.cpp.o
.PHONY : src/models/pose_detector_movenet.o

# target to build an object file
src/models/pose_detector_movenet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/pose_detector_movenet.cpp.o
.PHONY : src/models/pose_detector_movenet.cpp.o

src/models/pose_detector_movenet.i: src/models/pose_detector_movenet.cpp.i
.PHONY : src/models/pose_detector_movenet.i

# target to preprocess a source file
src/models/pose_detector_movenet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/pose_detector_movenet.cpp.i
.PHONY : src/models/pose_detector_movenet.cpp.i

src/models/pose_detector_movenet.s: src/models/pose_detector_movenet.cpp.s
.PHONY : src/models/pose_detector_movenet.s

# target to generate assembly for a file
src/models/pose_detector_movenet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/pose_detector_movenet.cpp.s
.PHONY : src/models/pose_detector_movenet.cpp.s

src/models/yolox_utils.o: src/models/yolox_utils.cpp.o
.PHONY : src/models/yolox_utils.o

# target to build an object file
src/models/yolox_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/yolox_utils.cpp.o
.PHONY : src/models/yolox_utils.cpp.o

src/models/yolox_utils.i: src/models/yolox_utils.cpp.i
.PHONY : src/models/yolox_utils.i

# target to preprocess a source file
src/models/yolox_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/yolox_utils.cpp.i
.PHONY : src/models/yolox_utils.cpp.i

src/models/yolox_utils.s: src/models/yolox_utils.cpp.s
.PHONY : src/models/yolox_utils.s

# target to generate assembly for a file
src/models/yolox_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/models/yolox_utils.cpp.s
.PHONY : src/models/yolox_utils.cpp.s

src/processors/fitness/pushup_analyzer.o: src/processors/fitness/pushup_analyzer.cpp.o
.PHONY : src/processors/fitness/pushup_analyzer.o

# target to build an object file
src/processors/fitness/pushup_analyzer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/processors/fitness/pushup_analyzer.cpp.o
.PHONY : src/processors/fitness/pushup_analyzer.cpp.o

src/processors/fitness/pushup_analyzer.i: src/processors/fitness/pushup_analyzer.cpp.i
.PHONY : src/processors/fitness/pushup_analyzer.i

# target to preprocess a source file
src/processors/fitness/pushup_analyzer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/processors/fitness/pushup_analyzer.cpp.i
.PHONY : src/processors/fitness/pushup_analyzer.cpp.i

src/processors/fitness/pushup_analyzer.s: src/processors/fitness/pushup_analyzer.cpp.s
.PHONY : src/processors/fitness/pushup_analyzer.s

# target to generate assembly for a file
src/processors/fitness/pushup_analyzer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/processors/fitness/pushup_analyzer.cpp.s
.PHONY : src/processors/fitness/pushup_analyzer.cpp.s

src/processors/image_processors/img_utils.o: src/processors/image_processors/img_utils.cpp.o
.PHONY : src/processors/image_processors/img_utils.o

# target to build an object file
src/processors/image_processors/img_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/processors/image_processors/img_utils.cpp.o
.PHONY : src/processors/image_processors/img_utils.cpp.o

src/processors/image_processors/img_utils.i: src/processors/image_processors/img_utils.cpp.i
.PHONY : src/processors/image_processors/img_utils.i

# target to preprocess a source file
src/processors/image_processors/img_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/processors/image_processors/img_utils.cpp.i
.PHONY : src/processors/image_processors/img_utils.cpp.i

src/processors/image_processors/img_utils.s: src/processors/image_processors/img_utils.cpp.s
.PHONY : src/processors/image_processors/img_utils.s

# target to generate assembly for a file
src/processors/image_processors/img_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/processors/image_processors/img_utils.cpp.s
.PHONY : src/processors/image_processors/img_utils.cpp.s

src/processors/signal_processors/signal_smoothing.o: src/processors/signal_processors/signal_smoothing.cpp.o
.PHONY : src/processors/signal_processors/signal_smoothing.o

# target to build an object file
src/processors/signal_processors/signal_smoothing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/processors/signal_processors/signal_smoothing.cpp.o
.PHONY : src/processors/signal_processors/signal_smoothing.cpp.o

src/processors/signal_processors/signal_smoothing.i: src/processors/signal_processors/signal_smoothing.cpp.i
.PHONY : src/processors/signal_processors/signal_smoothing.i

# target to preprocess a source file
src/processors/signal_processors/signal_smoothing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/processors/signal_processors/signal_smoothing.cpp.i
.PHONY : src/processors/signal_processors/signal_smoothing.cpp.i

src/processors/signal_processors/signal_smoothing.s: src/processors/signal_processors/signal_smoothing.cpp.s
.PHONY : src/processors/signal_processors/signal_smoothing.s

# target to generate assembly for a file
src/processors/signal_processors/signal_smoothing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/processors/signal_processors/signal_smoothing.cpp.s
.PHONY : src/processors/signal_processors/signal_smoothing.cpp.s

src/processors/signal_processors/z_score_filter.o: src/processors/signal_processors/z_score_filter.cpp.o
.PHONY : src/processors/signal_processors/z_score_filter.o

# target to build an object file
src/processors/signal_processors/z_score_filter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/processors/signal_processors/z_score_filter.cpp.o
.PHONY : src/processors/signal_processors/z_score_filter.cpp.o

src/processors/signal_processors/z_score_filter.i: src/processors/signal_processors/z_score_filter.cpp.i
.PHONY : src/processors/signal_processors/z_score_filter.i

# target to preprocess a source file
src/processors/signal_processors/z_score_filter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/processors/signal_processors/z_score_filter.cpp.i
.PHONY : src/processors/signal_processors/z_score_filter.cpp.i

src/processors/signal_processors/z_score_filter.s: src/processors/signal_processors/z_score_filter.cpp.s
.PHONY : src/processors/signal_processors/z_score_filter.s

# target to generate assembly for a file
src/processors/signal_processors/z_score_filter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daisykitsdk.dir/build.make CMakeFiles/daisykitsdk.dir/src/processors/signal_processors/z_score_filter.cpp.s
.PHONY : src/processors/signal_processors/z_score_filter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... configs"
	@echo "... images"
	@echo "... models"
	@echo "... ncnn-generate-spirv"
	@echo "... ZXing"
	@echo "... daisykitsdk"
	@echo "... demo_background_matting"
	@echo "... demo_barcode_scanner"
	@echo "... demo_face_detector"
	@echo "... demo_face_detector_graph"
	@echo "... demo_face_detector_scrfd"
	@echo "... demo_face_sequential"
	@echo "... demo_graph_api"
	@echo "... demo_hand_detector_yolox"
	@echo "... demo_hand_pose_detector"
	@echo "... demo_movenet"
	@echo "... demo_object_detector"
	@echo "... demo_pushup_classifier"
	@echo "... demo_pushup_full"
	@echo "... ncnn"
	@echo "... src/common/io/data_reader.o"
	@echo "... src/common/io/data_reader.i"
	@echo "... src/common/io/data_reader.s"
	@echo "... src/common/profiler.o"
	@echo "... src/common/profiler.i"
	@echo "... src/common/profiler.s"
	@echo "... src/common/utils/timer.o"
	@echo "... src/common/utils/timer.i"
	@echo "... src/common/utils/timer.s"
	@echo "... src/common/visualizers/base_visualizer.o"
	@echo "... src/common/visualizers/base_visualizer.i"
	@echo "... src/common/visualizers/base_visualizer.s"
	@echo "... src/flows/background_matting_flow.o"
	@echo "... src/flows/background_matting_flow.i"
	@echo "... src/flows/background_matting_flow.s"
	@echo "... src/flows/barcode_scanner_flow.o"
	@echo "... src/flows/barcode_scanner_flow.i"
	@echo "... src/flows/barcode_scanner_flow.s"
	@echo "... src/flows/face_detector_flow.o"
	@echo "... src/flows/face_detector_flow.i"
	@echo "... src/flows/face_detector_flow.s"
	@echo "... src/flows/hand_pose_detector_flow.o"
	@echo "... src/flows/hand_pose_detector_flow.i"
	@echo "... src/flows/hand_pose_detector_flow.s"
	@echo "... src/flows/human_pose_movenet_flow.o"
	@echo "... src/flows/human_pose_movenet_flow.i"
	@echo "... src/flows/human_pose_movenet_flow.s"
	@echo "... src/flows/object_detector_flow.o"
	@echo "... src/flows/object_detector_flow.i"
	@echo "... src/flows/object_detector_flow.s"
	@echo "... src/flows/pushup_counter_flow.o"
	@echo "... src/flows/pushup_counter_flow.i"
	@echo "... src/flows/pushup_counter_flow.s"
	@echo "... src/graphs/core/connection.o"
	@echo "... src/graphs/core/connection.i"
	@echo "... src/graphs/core/connection.s"
	@echo "... src/graphs/core/graph.o"
	@echo "... src/graphs/core/graph.i"
	@echo "... src/graphs/core/graph.s"
	@echo "... src/graphs/core/node.o"
	@echo "... src/graphs/core/node.i"
	@echo "... src/graphs/core/node.s"
	@echo "... src/graphs/core/packet.o"
	@echo "... src/graphs/core/packet.i"
	@echo "... src/graphs/core/packet.s"
	@echo "... src/graphs/core/transmission_profile.o"
	@echo "... src/graphs/core/transmission_profile.i"
	@echo "... src/graphs/core/transmission_profile.s"
	@echo "... src/models/action_classifier.o"
	@echo "... src/models/action_classifier.i"
	@echo "... src/models/action_classifier.s"
	@echo "... src/models/background_matting.o"
	@echo "... src/models/background_matting.i"
	@echo "... src/models/background_matting.s"
	@echo "... src/models/body_detector.o"
	@echo "... src/models/body_detector.i"
	@echo "... src/models/body_detector.s"
	@echo "... src/models/face_detector.o"
	@echo "... src/models/face_detector.i"
	@echo "... src/models/face_detector.s"
	@echo "... src/models/face_recognition/face_alignment.o"
	@echo "... src/models/face_recognition/face_alignment.i"
	@echo "... src/models/face_recognition/face_alignment.s"
	@echo "... src/models/face_recognition/face_detector_scrfd.o"
	@echo "... src/models/face_recognition/face_detector_scrfd.i"
	@echo "... src/models/face_recognition/face_detector_scrfd.s"
	@echo "... src/models/face_recognition/face_extractor.o"
	@echo "... src/models/face_recognition/face_extractor.i"
	@echo "... src/models/face_recognition/face_extractor.s"
	@echo "... src/models/face_recognition/face_manager.o"
	@echo "... src/models/face_recognition/face_manager.i"
	@echo "... src/models/face_recognition/face_manager.s"
	@echo "... src/models/facial_landmark_detector.o"
	@echo "... src/models/facial_landmark_detector.i"
	@echo "... src/models/facial_landmark_detector.s"
	@echo "... src/models/hand_detector_yolox.o"
	@echo "... src/models/hand_detector_yolox.i"
	@echo "... src/models/hand_detector_yolox.s"
	@echo "... src/models/hand_pose_detector.o"
	@echo "... src/models/hand_pose_detector.i"
	@echo "... src/models/hand_pose_detector.s"
	@echo "... src/models/image_model.o"
	@echo "... src/models/image_model.i"
	@echo "... src/models/image_model.s"
	@echo "... src/models/liveness_detector.o"
	@echo "... src/models/liveness_detector.i"
	@echo "... src/models/liveness_detector.s"
	@echo "... src/models/ncnn_model.o"
	@echo "... src/models/ncnn_model.i"
	@echo "... src/models/ncnn_model.s"
	@echo "... src/models/object_detector_yolox.o"
	@echo "... src/models/object_detector_yolox.i"
	@echo "... src/models/object_detector_yolox.s"
	@echo "... src/models/pose_detector.o"
	@echo "... src/models/pose_detector.i"
	@echo "... src/models/pose_detector.s"
	@echo "... src/models/pose_detector_movenet.o"
	@echo "... src/models/pose_detector_movenet.i"
	@echo "... src/models/pose_detector_movenet.s"
	@echo "... src/models/yolox_utils.o"
	@echo "... src/models/yolox_utils.i"
	@echo "... src/models/yolox_utils.s"
	@echo "... src/processors/fitness/pushup_analyzer.o"
	@echo "... src/processors/fitness/pushup_analyzer.i"
	@echo "... src/processors/fitness/pushup_analyzer.s"
	@echo "... src/processors/image_processors/img_utils.o"
	@echo "... src/processors/image_processors/img_utils.i"
	@echo "... src/processors/image_processors/img_utils.s"
	@echo "... src/processors/signal_processors/signal_smoothing.o"
	@echo "... src/processors/signal_processors/signal_smoothing.i"
	@echo "... src/processors/signal_processors/signal_smoothing.s"
	@echo "... src/processors/signal_processors/z_score_filter.o"
	@echo "... src/processors/signal_processors/z_score_filter.i"
	@echo "... src/processors/signal_processors/z_score_filter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

